# Numpy

**NumPy** là viết tắt của "Numerical Python", là một library chuyên để xử lý các vấn đề liên quan đến Đại số tuyến tính như: vector, ma trận, gần như các library quan trọng của Python sử dụng trong Data Science đều được build trên nền `Numpy`. Tốc độ thực thi trên `Numpy` **nhanh hơn rất nhiều** so với trên `list` mặc định của Python.

Ngoài ra, 1 điểm mạnh khác của NumPy so với Python mặc định là có thể mô phỏng được **mảng nhiều chiều (multi-dimensional arrays)**

![NumPy Array](https://lh3.googleusercontent.com/FupEwjNSPGKcOgrw4yczZlcnOpnqZSyp0twsldHa22YOp8b9625ywBKIcxN5iq0peY84oEdsEqEU7AFGBHTE8Xz6AJLJLvaUr_gYz8XDtWOczcdymDCN2rABzspCIUWVP0d1N2lOsfbxXYE_Vyo6gGNTtqiHTjnBAVu3s8R5_jagCSEQerMst0TUPwrvoYmWgkuhHt-umtIS52CDLQa0d57wSa8Gtd8msgRBrjMYBWsOHhhk311LhE68TkusVmWscV-WpRV87kG0tjOQW02cWMC4sxcTctymq4fXsq2cDY1YPHeRuwFrViwTABroi_O9cJefeSzKIZJ2SSaodeRmhDnoshBpDlWSb9-KPSuTs4s-kZwc64V7XhKDV0aoRZFYC1FPYXDviQML-LXk8-g16WnI3ycznJHIwHFaa5XbG0g7c1Edy6N600TUqNMpJzAleq7EON1xcUHQ0rljTt5rky5NmU6DB1yvtH54gKUK8pVG4tlA12C6shkJnl93u1xwwJKeoKmn4MD7UqZNi3-DWzLaLKrhbz4gAM8kz_FthQIa7Y0R750OMS88lNy0tQwliRpNZS5-7-g3xxriVQ1DO8dAyzOY2ntFuE-KfmPH66etxbtm9PvZnsIcp-3QIST4CNu-P4Jmv7pSSqLlErNAxwIZT1nugJN26g=w798-h189-no)

Ảnh từ [DataCamp](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

## Cài đặt numpy

Khi cài đặt **Anaconda**, `numpy` thường được cài sẵn, còn nếu ko chúng ta có thể tự cài
```
# using conda
conda install numpy

#using pip
pip install numpy
```

Gọi library

In [1]:
import numpy as np

## Khởi tạo numpy array

Trong `numpy`, chúng ta sẽ làm việc chủ yếu với đối tượng là `numpy array`, trong đó có 2 loại chính là 1-array và 2-array, có thể hiểu 1-array là vector - mảng 1 chiều, 2-array là matrix - mảng 2 chiều

### Sử dụng cấu trúc `np.array()`

- Mảng 1 chiều: dữ liệu đưa vào là 1 list

In [2]:
import numpy as np
one_array = np.array([1, 2, 3, 5])
one_array

array([1, 2, 3, 5])

In [3]:
type(one_array)

numpy.ndarray

Có thể đọc từ dataframe (chúng ta sẽ tạm sử dụng pandas)

In [4]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df_col = np.array(df['embark_town'].head(5))
df_col

array(['Southampton', 'Cherbourg', 'Southampton', 'Southampton',
       'Southampton'], dtype=object)

- Mảng 2 chiều: dữ liệu đưa vào là 1 list, trong đó mỗi phần tử lại là 1 list con

In [5]:
two_array = np.array([[1, 2, 5], [2, 5, 7]])
two_array

array([[1, 2, 5],
       [2, 5, 7]])

- Mảng 3 chiều

In [6]:
three_array = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
])
three_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
three_array.shape

(2, 2, 3)

Điểm khác biệt của `numpy array` với `list`:
- Kiểu dữ liệu của các phần tử phải đồng nhất
- Kiểu dữ liệu phải nằm trong các kiểu dữ liệu (`dtypes`) của `Numpy`, trong đó các kiểu dữ liệu quan trọng nhất là:
    - float64: 64 bit floating point number
    - int64: 64 bit integer
    - bool: 8 bit True or False

### Built-in methods

#### zeros, ones, full

Đây là các method tạo ra các trị bằng nhau, phù hợp để tạo ra các mảng lớn. Trong đó
    - zeros(): tạo ra các mảng có các phần tử = 0 
    - ones(): tạo ra các mảng có các phần tử = 1
    - full(): tạo ra các mảng có các phần tử = 1 giá trị nhập vào
Đầu vào đều là **tuple**    

In [8]:
# Mảng bao gồm 10 số 0, kiểu dữ liệu integer
np_zero1 = np.zeros(10, dtype=int)
np_zero1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Mảng float 3*2
np_ones = np.ones((3,2), dtype = float)
np_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Mảng 3*5 với các phần tử là 3.14
np_full = np.full((3, 5), 3.14)
np_full

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Tương tự với mảng 3 chiều

#### np.eye(): Tạo ma trận đơn vị

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### np.diag(): Tạo ma trận đường chéo

In [12]:
np.diag([1, 3, 4])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

#### np.linspace()

In [13]:
# Trả ra 1 array có giá trị từ 0 -20 và có 10 phần tử
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

#### np.arange()

In [14]:
# Tạo 1 Array giá trị chạy từ 0 -> 10
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
# Tạo mảng giá trị từ 0 - 20, cách nhau 2 đơn vị
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Random
`Numpy` cung cấp rất nhiều cách để tạo ra các giá trị ngẫu nhiên

**np.random.random()**

In [16]:
# 1 số
np.random.random()

0.8303289714145884

In [17]:
# Mảng 1 chiều - vector 
np.random.random(5)

array([0.8560534 , 0.54214177, 0.46585143, 0.46525173, 0.08072976])

In [18]:
# Mảng 2 chiều - ma trận
np.random.random((3,4))

array([[0.97482556, 0.10191368, 0.62953872, 0.3295818 ],
       [0.38492982, 0.96324629, 0.80224336, 0.86347924],
       [0.63901262, 0.18255819, 0.05759006, 0.68912514]])

**np.random.rand**: các giá trị ngẫu nhiên phân phối đều trong khoảng `[0, 1)`

In [19]:
np.random.rand(3,5)

array([[0.76055491, 0.77373106, 0.28586801, 0.69804029, 0.45050567],
       [0.12396176, 0.08092196, 0.2278207 , 0.82617292, 0.68669953],
       [0.12680203, 0.06584246, 0.56146037, 0.89490173, 0.45792336]])

**np.random.randn(5, 5)**: các giá trị ngẫu nhiên phân phối chuẩn

In [20]:
np.random.randn(3,5)

array([[-0.16975378,  0.32129981,  0.37932254, -0.00889893,  0.95655219],
       [-0.18819489,  0.53228413,  1.71395677,  0.14244804,  0.58681277],
       [-0.86652071, -0.25812345, -0.88723547, -1.50178007, -1.27698409]])

**np.random.randint:** tạo mảng ngẫu nhiên gồm toàn integer

In [21]:
np.random.randint(low = 1, high = 10, size = 10)

array([7, 4, 4, 3, 2, 6, 5, 2, 4, 3])

## Array manipulation

Chúng ta sẽ đi qua các mục như sau:
- Method & attributes
- Index & slicing
- Reshaping arrays
- Concatenating & splitting

### Array methods & attributes

Set seed value để make sure rằng các mảng random được tạo ra sau mỗi lần generate là giống nhau

In [22]:
np.random.seed(0)

In [23]:
x1 = np.random.randint(10, size = (2, 3))
x2 = np.random.randint(10, size = (2, 3, 4))

In [24]:
x1

array([[5, 0, 3],
       [3, 7, 9]])

In [25]:
x2

array([[[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]],

       [[8, 1, 5, 9],
        [8, 9, 4, 3],
        [0, 3, 5, 0]]])

Các `attribute` thường sử dụng là **shape**, **ndim**, **size** và **dtype**

In [26]:
print("x2 ndim: ", x2.ndim) # dimension
print("x2 shape:", x2.shape) # shape 
print("x2 size: ", x2.size) # số phần tử
print("x2.dtype:  ", x2.dtype) # kiểu dữ liệu

x2 ndim:  3
x2 shape: (2, 3, 4)
x2 size:  24
x2.dtype:   int32


**Một số method khác**

In [27]:
x3 = np.random.rand(8)
x3

array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892])

In [28]:
x3.sort()
x3

array([0.11827443, 0.14335329, 0.46147936, 0.63992102, 0.78052918,
       0.79915856, 0.94466892, 0.97861834])

In [29]:
x3.sum() # tương tự với mean, max, min

4.866003096643962

In [30]:
x1

array([[5, 0, 3],
       [3, 7, 9]])

In [31]:
x1.T #transpose

array([[5, 3],
       [0, 7],
       [3, 9]])

### Index & slicing:
Khá tương tự với list trong Python.

Việc mô phỏng ma trận nhiều chiều của NumPy dựa trên việc sử dụng list bên trong list (nested list) cho nên việc truy cập các phần tử trong mảng này hoàn toàn tương tự như chúng ta đã thực hiện trong Python.

In [32]:
np_2D = np.array([[2,3,4], [4, 7, 8]])

In [33]:
np_2D

array([[2, 3, 4],
       [4, 7, 8]])

- Truy cập hàng

In [34]:
# Truy cập hàng đầu 
np_2D[0]

array([2, 3, 4])

In [35]:
# Truy cập hàng cuối cùng
np_2D[-1]

array([4, 7, 8])

- Truy cập cột

In [36]:
# Lấy cột thứ 2
np_2D[:, 1] # Dấu : thể hiện duyệt qua tất cả các hàng ", 1" là lấy cột thứ 2

array([3, 7])

- Truy cập 1 mảng trong ma trận

In [37]:
awesome = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 4, 5, 8, 9, 0],
    [2, 9, 7, 8, 0, 4, 5],
    [9, 6, 4, 9, 3, 7, 2],
])

Sẽ lấy 1 ma trận con như ở dưới

![Matrix](https://lh3.googleusercontent.com/pxLKL0NUTZMwxXULMx0C6oWO2f5ysUd2egfi684gIF7hPPgaW6mwj5qF9jkqhJlEkT7MSfL9EaXJ1ygUsm0zqk4IjsZ6WHAvha76gz0qql_zeMoLU_HKvIU_4qVOCzny_6Zugp7NnKA9vLYThpWznMWxNdZPK5WjG6PLWGFMMS0mekVbLxHXWAmqNHln13Mt4dZfs8BJIzDnZolx9ntYH7v_0QezyZyXZIGKs_4UHTNTWK2pbe8ynVKgm2eTtUiZB0wrPzawRHRfbmuaiLuQ7b7zR2AYErfKvAzmH8DIo5V2dBxrxNjiyQaMWjWS-wzHthWAf71ZAx1VidbOmoRJTkRMFsxcFJ6xzn35ohFw7VnJpUkp2gNcLd0Lxv4gNphZQX6JV4ZEzKzZuTCBJ7-2C-ZIyyGRNIIfCGSYsZgWQEl23BUg_zxTYnzsL3pn44FHzyJxYpZkZd_JJ50SzH1G514hCC28Z67sO9_HfeHrl5seOd73nZk6j2Nnli5x4d09QaH3FiAMBWHb6JcroRs0RvAwbyNGGwiAbm-JTucXTP3sq6yhH6KZQM1SeeidiUdoKzxKdRihWo6ush0zUC-yumQIz4DUJEYrnKMT2bNnhj2Ml2OT_K1tf2RGtKdpGoxWT-LsAv75B3ERebwxIqPv3Z0J6jF2WSdBmw=w445-h222-no)

In [38]:
awesome[1:3, 2:4]

array([[4, 5],
       [7, 8]])

Truy cập 1 phần tử

![](https://lh3.googleusercontent.com/o8aJwfEiYr0PuhFO2Dd1dj1I9rlvNk-w0OG12Z5a-OpUt0fpMHTO-JejM2ljn5hlZI5DaHY7Hhv_TR5-qPwWtfOyWWBQ2Ut8Iuiy_5ksmC_c2GARBVN-0rpCERKb4Anp2ieUY1R1N4JBWFNFSL3z4V3O55q3-embqrXChbnVMl9VzQFXUKOwTrWn7lYEMOgxNNQElY4nGmfOBFTVc3ZpNGJF968xwvyV2e1W-3v2IGqluN8TDO08euNSek7GsiP7aFhB6LIBKnkiOXYH8rPcpDyUjB2Coc8d4hf0_TQKMoiZA5Xki5meL0IsRZWk1wYTotMSMbr-znGrAKv_pWGFb7ti3eFazkwdavyGr2YKlq3qJsg2cvRpaL76VxKeK4mdu6l3Wj7VpqL2GJWFuE9KsYx7RauzeKN0h2bgIu4sASBmZ8RIhVJMAqZK3hxi9eEl55_StyQZ5WtsKBFSoz6urxqfSGcMPAKEjjl8JDg6jGvyn0uECXMfTgWBUXURGTslauyvQw2RIlt9axMG_mHXgmT5kWSewlZc-68FiFW5igB_ilMOD8Kbfs7J-Uyhtw6jsNzo83cIaVUI8hUGUcHMCEKmYeJA2fhSmflS4BI06vh2GpGswzHrN5Rrb6PA9YFwyw4SbjcDeVMoFLiOxv0aX4LjV4lIk9IYYg=w445-h222-no)

In [39]:
awesome[1, 2]

4

In [40]:
# tương đương với
awesome[1][2]

4

#### Sub-array copy

Một concept hết sức quan trọng để tránh gây nhầm lẫn sau này khi slice 1 array trong `numpy`, không có array nào thực sự được tạo ra mà chỉ là tạo ra 1 `view` refer đến array cũ, mọi thay đổi trong array mới tạo đều sẽ tạo nên sự thay đổi trong array cũ, điều này khác biệt với **list**

In [41]:
# tạo 1 array
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
# slice array và update giá trị bằng 99
arr_slice = arr1[3:8]
arr_slice[:] = 99
arr_slice

array([99, 99, 99, 99, 99])

In [43]:
# Kiểm tra array ban đầu chúng ta thấy giá trị đã bị thay đổi
arr1

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Cách làm này rất hữu dụng với những TH phải làm việc với tập dataset lớn, tuy nhiên đôi khi chúng ta vẫn cần tạo 1 array mới phân biệt với array ban đầu, để làm việc này chúng ta sử dụng `copy()` method

In [44]:
arr_slice = arr1[3:8].copy()
arr_slice[:] = 88
arr1 # dữ liệu gốc không bị thay đổi

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Reshaping array

**reshape**: Thay đổi shape của array, với điều kiện size của array ban đầu phải match với size của array được reshape

In [45]:
# Reshape mảng 1 chiều --> mảng 2 chiều
array_2D = np.arange(1, 10).reshape(3,3)
array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# reshape sang 1 array mới ko cùng kích thước --> báo lỗi
np.arange(1, 10).reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

**flaten**: "duỗi" từ mảng nhiều chiều về 1 chiều

In [47]:
array_2D.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**transpose:** trả về ma trận chuyển vị

In [48]:
# ma tran 2x3
matrix_23 = np.array([[2, 4, 6], [3, 5, 7]])
matrix_23

array([[2, 4, 6],
       [3, 5, 7]])

In [49]:
# Chuyển vị về ma trận 3x2
matrix_23.transpose()

array([[2, 3],
       [4, 5],
       [6, 7]])

![transpose](https://lh3.googleusercontent.com/9a1m0a1kozsZtPgffI2fAsgm2nnRymGYVgp3EXjXnHTZqBe-O5IT-WLT4N1r_2HsK_vP16ssazkAQvmh4ccv1-rMCZDA5f1llpvkqZFC7_ZFmNpVXXNkKHhenen0DXfzS1NqauBRiThtxxrnqvs6DjiHNv3o6z9QPOTuq19cWz9TBU2mkJKEMihglnKdKlNJa2l05WeBmJwAcpjwSQft5jlrn6kr9X782n9jPuC32pE7SOtIEzVSdV_DoRZMonrOnRRGsiz1bJFSumC9gaAaTx-kqGQbf6sKU3avjzNe6Elyg36MkwEfWAbCR9kMGXZ9shkgh41ymTLCNfqsqWuX2DrcfXbwNCjwj17IHeAeITYJoIP-W1lEk0yC7faQUmUh_OSpxG2Km5GFVQQxEj1SeNOW-k0jLyzjYuoyhLX3AGEYaHuDk81a4_HFRpg9fAD6aOGkQHNPghQrA2BQW9FgFK3pL6JDqtbuGQd9mz-KIjHSDTBm1OpQwxXMAnfYr6V0Jq4fULBKCCd96IZC_eJRxIFY_Za_cegK7FYIla9s7ggBg_n7zlAF7V9-BFJcZ9eVl6-_8UhUT20xdSkWERnqwtGwiikEDf5mbzg9iNjktPswaqqd3Y-JupOCH8KdLF5MgXAhexeb6SlWAuu55gy4ucR62iRZj7tan5fjyBlcT-ZqHOhZEXSxGoqEcQ=w800-h400-no)

### Concatenating & spliting arrays

**Concatenating**

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([9, 9, 9])
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 9, 9, 9])

trường hợp số dimension khác nhau, có thể sử dụng `hstack` hoặc `vstack`

In [51]:
#vstack - combine theo chiều dọc
t = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.vstack([x, t])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
#hstack - combine theo chiều ngang
s = np.array([[9], [7]])
np.hstack([t, s])

array([[1, 2, 3, 9],
       [4, 5, 6, 7]])

**Splitting**

In [53]:
np.split(arr1, [3, 5, 7]) # tách theo 3 vị trí 3, 5, 7 ---> 4 array

[array([0, 1, 2]),
 array([99, 99]),
 array([99, 99]),
 array([99,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

### Fancy indexing

Ngoài các công cụ để truy cập dữ liệu như _index_ (ví dụ `arr[0]`) , _slicing_ (`arr[0:3]`) và _masking_ (`arr[arr>3]`), numpy array có 1 công cụ khác khá hữu hiệu mà `list` ko có là _fancy indexing_, cho phép chúng ta sử dụng **mảng** để làm index thay vì số như bình thường, để hiểu hơn hãy xem các ví dụ ở dưới

In [56]:
import numpy as np
x = np.random.randint(100, size=10)
print(x)

[36 53  5 38 17 79  4 42 58 31]


Giả sử chúng ta muốn lấy 3 phần tử có số thứ tự là 3, 7, 4, thay vì viết: 
```
[x[3], x[7], x[4]]
```
như với list, chúng ta có thể đưa 3, 7, 4 thành 1 list và sử dụng như 1 index

In [57]:
x[[3,7,4]]

array([38, 42, 17])

hoặc

In [58]:
ind = [3, 7, 4]
x[ind]

array([38, 42, 17])

`fancy index` cũng áp dụng cho các trường hợp từ 2-dimension trở lên

In [59]:
y = np.arange(12).reshape((3, 4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
row = np.array([1, 2])
col = np.array([3, 2, 1])

In [61]:
y[row, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
y[:, col]

array([[ 3,  2,  1],
       [ 7,  6,  5],
       [11, 10,  9]])

## Comparison, mask & boolean

### Comparison

In [63]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
x < 3

array([ True,  True,  True, False, False, False, False])

In [65]:
x == 3

array([False, False, False,  True, False, False, False])

In [66]:
x != 3

array([ True,  True,  True, False,  True,  True,  True])

In [67]:
2 * x == x ** 2

array([ True, False,  True, False, False, False, False])

In [68]:
y = np.random.randint(10, size = (3,5))

In [69]:
y

array([[8, 1, 1, 7, 9],
       [9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4]])

In [70]:
y ** 2 == 9

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

### Boolean arrays

In [71]:
# count - nonzero - đếm số giá trị là True
np.count_nonzero(y > 5)

7

In [72]:
# Tương tự có thể dùng sum, các giá trị FALSE được tính là 0, TRUE là 0
np.sum(y > 5)

7

In [73]:
np.sum((y > 5) & (y < 7))

1

In [74]:
# Có giá trị nào bằng 8 ko ? 
np.any(y == 8)

True

In [75]:
# tất cả giá trị > 5 đúng ko ?
np.all(y > 5)

False

### Boolean arrays as Masks

Tách 1 mảng con từ mảng ban đầu theo điều kiện

In [76]:
y[y>5]

array([8, 7, 9, 9, 6, 7, 9])

## Broadcasting - phép lan truyền

![title](Image/Broadcast1.png)

Broadcasting là cách chúng ta thay đổi cùng lúc nhiều phần tử của 1 array.
Cụ thể hơn, broadcasting là 1 tập hợp các rules cho phép tính toán (cộng, trừ, nhân ...) với những mảng có số chiều khác nhau

![title](Image/Broadcast2.png)

Ví dụ 1 phép tính thông thường giữa 2 mảng cùng chiều

In [77]:
a = np.array([5, 7, 0])
b = np.array([2, 8, 1])
a + b

array([ 7, 15,  1])

- Broadcasting mảng vs số

![title](Image/Broadcast3.png)

In [78]:
a + 3

array([ 8, 10,  3])

Như ta thấy, **3** cộng với tất cả các phần tử của a
--> Numpy đã chuyển số 3 thành 1 mảng 3 chiều để thực hiện phép cộng

In [79]:
# tương đương với
a + np.array([3, 3, 3])

array([ 8, 10,  3])

In [80]:
# mảng số 2 chiều
a_2D = np.asarray([
    [4, 5, 6], 
    [7, 8, 9]
])

In [81]:
a_2D + 2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

Tương tự với phép nhân

- Broadcasting mảng với mảng

![title](Image/Broadcast4.png)

## Universal numpy function

Numpy cung cấp khá đầy đủ các hàm tính toán tương tự như Python gốc, tuy nhiên điểm khác biệt căn bản - cũng là ưu điểm lớn của `numpy` đó là các hàm này đều là `vectorized operation`, tức là sẽ tính toán theo từng phần tử - vì vậy các hàm này còn gọi là **universal function** - **UFuncs**

In [85]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

câu lệnh tương tự với list dưới đây sẽ báo lỗi

In [86]:
from math import sin
t = [1, 2, 3]
sin(t)

TypeError: must be real number, not list

và chỉ có thể sử dụng `list comprehesion` như đã học ở bài trước, hoặc cũng có thể dùng vòng lặp

In [87]:
[sin(i) for i in t]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [88]:
l1 = []
for i in t:
    l1.append(sin(i))
l1

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

## Linear Algebra 

- Tích vô hướng 2 vector

In [89]:
import numpy as np 

In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [91]:
np.inner(a, b)

32

- Tích vô hướng 2 ma trận

In [92]:
m1 = np.array([
                [1, 32, 3],
                [6, 7, 4]
            ])

In [93]:
m2 = np.array([
    [5, 6],
    [7, 8]
])

In [94]:
np.dot(m2, m1)

array([[ 41, 202,  39],
       [ 55, 280,  53]])

**Chú ý: np.dot(A, B) <> np.dot(B, A)**

- Chuyển vị ma trận

In [95]:
np.transpose(m1)

array([[ 1,  6],
       [32,  7],
       [ 3,  4]])

In [96]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [97]:
x = np.array([-2, -1, 0, 1, 2])
y = [-2, -1, 0, 1, 2]
abs(x) 

array([2, 1, 0, 1, 2])

In [98]:
abs(y)

TypeError: bad operand type for abs(): 'list'